// Code generated by "stringer -type=PowerState -trimprefix=PowerState -linecomment"; DO NOT EDIT.

package cim

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PowerStateOn-2]
	_ = x[PowerStateSleepLight-3]
	_ = x[PowerStateSleepDeep-4]
	_ = x[PowerStateOffHard-6]
	_ = x[PowerStateHibernateOffSoft-7]
	_ = x[PowerStateOffSoft-8]
}

const (
	_PowerState_name_0 = "OnSleepLightSleepDeep"
	_PowerState_name_1 = "OffHardHibernateOffSoftOffSoft"
)

var (
	_PowerState_index_0 = [...]uint8{0, 2, 12, 21}
	_PowerState_index_1 = [...]uint8{0, 7, 23, 30}
)

func (i PowerState) String() string {
	switch {
	case 2 <= i && i <= 4:
		i -= 2
		return _PowerState_name_0[_PowerState_index_0[i]:_PowerState_index_0[i+1]]
	case 6 <= i && i <= 8:
		i -= 6
		return _PowerState_name_1[_PowerState_index_1[i]:_PowerState_index_1[i+1]]
	default:
		return "PowerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
