// Code generated by "stringer -type=bootConfigRole -trimprefix=bootConfigRole -linecomment"; DO NOT EDIT.

package amt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[bootConfigRoleIsNext-0]
	_ = x[bootConfigRoleIsNextSingleUse-1]
	_ = x[bootConfigRoleIsDefault-2]
	_ = x[bootConfigRoleDMTFReserved-3]
	_ = x[bootConfigRoleVendorSpecified-32768]
}

const (
	_bootConfigRole_name_0 = "IsNextIsNextSingleUseIsDefault3..32767"
	_bootConfigRole_name_1 = "32768..65535"
)

var (
	_bootConfigRole_index_0 = [...]uint8{0, 6, 21, 30, 38}
)

func (i bootConfigRole) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _bootConfigRole_name_0[_bootConfigRole_index_0[i]:_bootConfigRole_index_0[i+1]]
	case i == 32768:
		return _bootConfigRole_name_1
	default:
		return "bootConfigRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
