name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make

    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet .
        golint .

    - name: Test
      run: go test -v ./...
